language: java

jdk:
  - oraclejdk7
  - openjdk6

install: mvn dependency:resolve -Dsilent -B

notifications:
  irc:
    channels:
      - "irc.freenode.org#phenotips"
    on_success: change
    on_failure: always
    use_notice: true
    skip_join: true
    template:
      - "%{repository} (%{branch}:%{commit} by %{author}): %{message} (%{build_url})" 